### ISSUE TITLE
Sourcemap

### ISSUE THREAD

**Issue by KarelWintersky** [pjeby/tag-wrangler#10]
Please, don't include SOURCEMAP code to production version!

It is more than 900 kb

**Comment by pjeby** [comment]
Heh, you should probably not use the CSV plugin, it's 14Mb, 2/3rds of which is the sourcemap.

I will consider changing this, but you should be aware that the default of the official example plugin is to include sourcemaps, and the majority of plugins I have installed include them.  Of the ones I have that don't include them, the majority of those are ones I wrote without using rollup or any external libraries.

Part of the reasoning for including sourcemaps in the distribution is that it allows other developers to debug another plugin more easily.  This needs to be traded off against memory use, of course, but ISTM that this use case might be better served by having Obsidian strip sourcemaps at install time, but keep both the minimal and debug version, and have an option to load a plugin's debug version.

The benefit of that is that it wouldn't require a plugin developer to predict in advance which version a user would like to load.

**Comment by KarelWintersky** [comment]
I use the same set of plugins for all of my vaults.

The same set of plugins in each vault eats up a lot of disk space. The trouble is that sourcemaps consume most of it.

**Comment by KarelWintersky** [comment]
See my PR solves same problem:

https://github.com/cristianvasquez/obsidian-prettify/pull/60

**Comment by pjeby** [comment]
Ok, you've successfully changed my mind.

From "I will consider this" (stated above) to "won't do this any time soon".

For future reference, spamming multiple notices and describing things as "bad" without respect for others use cases, are good ways to make me not care about someone's requests or needs.
