### ISSUE TITLE
Allow for looking for a tag in the tag tree view

### ISSUE THREAD

**Issue by Jeromandres** [pjeby/tag-wrangler#101]
I sometimes don't remember which name I actually put for a tag, or which prefix I used
(I use a two level tag nesting, the first one with a single letter).

Allowing for looking a tag by its name, with a query field that would filter progressively the list of tags would be nice.

I imagine a query symbol with an input zone, close to the other icons (after order, nest, collapse, expand).

**Comment by pjeby** [comment]
Future versions of tag wrangler will give you access to the tag from wherever it appears in Obsidian, which means you can just type `#` in a note followed by part of the tag name.  Obsidian will suggest tags, then you can just pick one, and finally right-click or contextmenu it to access the Tag Wrangler menu.

If that's all you need, just keep an eye out for the next Tag Wrangler release.

**Comment by luxhacker2** [comment]
+ 1 !!
Tagwrangler is a very good tool, and for users making extensive use of it, searching in a large tag list is very important.
And a history of the last selected tags would also be very helpful. 
Functionnalities could be called just list sort order and others, by clicking on a button on top of the list !
Thanks for this excellent tool (I do use rename extensively)
LH

**Comment by pjeby** [comment]
If you want filtering in the tags view, that's a feature you should make a feature request for on the Obsidian official forums; it's not something I plan to add to Tag Wrangler.

The other feature mentioned in this issue, whereby you can type a tag anywhere, get autocompletion, and then access the Tag Wrangler menu (via right click or context menu key), is now available in the current release, so I'm closing this issue now.

**Comment by luxhacker2** [comment]
Duly noted concerning filtering in the tags view. (Sorry, I am not sure that I understand where Tagwrangler is intervening, and where the "normal" Obsidian.)

I use autocompletion of tags, this is not what I was asking for. I would like to display in the tags sidebar the last *queried* tags. To reselect it. For old guys, whose memory is good but not always top ;)
