### ISSUE TITLE
Unable to view tag wrangler icon

### ISSUE THREAD

**Issue by thepalashthakur** [pjeby/tag-wrangler#105]
<img width="1291" alt="image" src="https://github.com/pjeby/tag-wrangler/assets/99094241/59456197-313d-4d71-ac2d-3599d20747e2">
Hello 
I recently installed the plugin in a new vault but it isn't visible in menu . Though I am able to use it in another vault where it was installed previously

**Comment by thepalashthakur** [comment]
OS: MacOS ventura
Obsidian Version:  1.3.7

**Comment by pjeby** [comment]
What does "isn't visible in menu" mean?  Tag Wrangler doesn't appear in any Obsidian menus.  Do you mean the tag pane isn't visible?  If so, use the "Tags: Show tags" command to open it.  If there's no such command in the command palette, go to Settings > Core Plugins and enable Tags.

**Comment by thepalashthakur** [comment]
@pjeby   tag pane is not visible as in screen shot, the plugin is installed and enabled.
