### ISSUE TITLE
Plugin doesn´t work on linux

### ISSUE THREAD

**Issue by Androtherion** [pjeby/tag-wrangler#106]
Update: I just realised it was my bad, the plugin works fine.

Using Tag Wrangler 0.5.11 with the v1.3.5 Obsidian Flatpak running on Ubuntu 22.04. Also tried with the official .deb package.

Unlike on windows 10, where the plugin works wonderfully, in linux it is impossible to edit tags, as righ-click a specific tag on the tag pane does nothing.

Also, if someone encounters the same problem, a brute-force workaround would be to change the tags by opening the vault on terminal and executing this command:
find . -type f -name "*.md" -print0 | xargs -0 sed -i 's/#OldTag/#NewTag/g'
Changing the "#OldTag" and "#NewTag". The problem is that it doesn't change tags on the frontmatter, wich can only be done by running the same command without the "#" but then substitutes iteration of the word in every note, not only tags.

**Comment by pjeby** [comment]
Thanks!
