### ISSUE TITLE
Can't drop tags in editor in Obsidian1.4.5

### ISSUE THREAD

**Issue by medusa11248** [pjeby/tag-wrangler#107]

**Comment by pjeby** [comment]
I don't understand.  Do you mean the collapse/expand functions in the Tag Wrangler menu?  Those seem to work just fine in 1.4.5.

**Comment by medusa11248** [comment]
I'm sorry. I mean the drag function is unavailable. I can't drag the tag into note to create a new tag in 1.4.5.

**Comment by medusa11248** [comment]
I'm so sorry. Please excuse my poor English.

**Comment by pjeby** [comment]
This should now be fixed in release 0.5.12; please let me know whether it works for you.  Thanks for the report.

**Comment by medusa11248** [comment]
The problem is solved. Thank you. :)
