### ISSUE TITLE
Tag Page backlinks

### ISSUE THREAD

**Issue by eltaho** [pjeby/tag-wrangler#112]
Hi,

I'm a bit confused, in the Tag Page description it's says: "In the meantime, however, you can use Obsidian's backlinks to find and change such references from the tag page."

When I tag in note properties (frontmatter) of a note it doesn't appear in the backlinks of a tag page. It does work if tag is in the body of a note only. 

Is it intentional or maybe there're some blocker that tags in the properties doesn't appear in "Unlinked mentions" of a tag page?

**Comment by pjeby** [comment]
That comment applies only to inline tags, not property tags.  You can't (usefully) put links in the tags property, so a semi-automated conversion isn't possible in that case.

**Comment by eltaho** [comment]
Now I see why, thanks. I wanted to use tags as a count indicator for notes and use it as a trigger when it's a moment to create MOC. So if the count of a category tag goes above the certain threshold, let's say 10 or 20, then I right click on it and create TAG PAGE (MOC).

**Comment by pjeby** [comment]
Yeah, if you want to switch property tags to links, you have to move them to a different property or move them into the body of the document.  For this workflow I'd suggest just not using property tags and putting them in the document as `#mytag` style tags, then you can use unlinked mentions and the link button to convert them to links.

Note, though, that you don't *have to* convert tags to links ever, if you don't want to.  I personally find that Obsidian's tag completion is enormously better than its link completion, at least for my size of vault.
