### ISSUE TITLE
"New search for ..." tags beginning with a dash return no results (`#-TEST`)

### ISSUE THREAD

**Issue by redactedscribe** [pjeby/tag-wrangler#113]
When right-clicking a tag which begins with dashes, e.g. `-TEST`, and selecting "New search for #-TEST", 0 results are shown in the Search sidebar. To return results, the search term must be modified from `tag:-TEST` to `tag:#-TEST`. The prepending of `#` for all tag searches doesn't appear to worsen results but only improve them (by accounting for edge cases such as this).

Maybe all "New search for ..." (and exclude) queries should include the hash symbol by default? When Obsidian autocompletes a tag after typing `tag:` into the search field, it also prepends a `#` to it by default.

Thanks.

Edit: Simply clicking on a tag in the Tags panel also searches for the tag and prepends a `#`.

**Comment by pjeby** [comment]
This should be fixed in 0.6.0, which I've just released.

**Comment by redactedscribe** [comment]
This looks like it's now working for new searching and excluding of tags. Thanks!
