### ISSUE TITLE
Delete tag command

### ISSUE THREAD

**Issue by gchegr** [pjeby/tag-wrangler#12]
Surprisingly, clearing a name of a tag does not delete it. On the other hand, it is indeed an 'invalid name'.
Still, sometimes there is a need to delete a tag from every note without using an external tools.
It should ask confirmation and/or allow undo, I think.

Thanks for patching the boat! It works great and seamless so far.

**Comment by pjeby** [comment]
Simply replacing a tag with an empty string won't handle a lot of cases, e.g. tags in a YAML field, comma separated list, tag as a list item, etc.  tag on a line by itself, etc.  That's one of the big reasons I don't plan to implement tag deletion in the near future.

**Comment by gchegr** [comment]
Yep, understandable, thanks for the reply.
Note: making a line empty is the most naïve way of doing that. A command in a context menu could work better.
Hope you change your mind. Again, my appreciation for the tool.

**Comment by MrBretticus** [comment]
Would be a great feature to have, but understand the complexity
