### ISSUE TITLE
[FEATURE] Detag / Remove something that's not a tag.

### ISSUE THREAD

**Issue by doug-w** [pjeby/tag-wrangler#133]
Importing notes from Evernote, I wound up with a lot of notes that had a tag of 1, because the original not talked about the `#1` thing to do.

I'd love a right click menu of a tag that isn't really a tag that would go through and change every use of it to `\#1` instead.

**Comment by pjeby** [comment]
You might find one of these helpful:

- https://obsidian.md/plugins?id=global-search-and-replace
- https://obsidian.md/plugins?id=obsidian-apply-patterns

(The latter is something you have to use on individual files, but you can set up a set of patterns you frequently use in its settings and apply a bunch at once.)

**Comment by Medullitus** [comment]
> You might find one of these helpful:
> 
>     * https://obsidian.md/plugins?id=global-search-and-replace
> 
>     * https://obsidian.md/plugins?id=obsidian-apply-patterns
> 
> 
> (The latter is something you have to use on individual files, but you can set up a set of patterns you frequently use in its settings and apply a bunch at once.)

Hello. Thank you for your reply. But instead of those can't you basically add a "remove" option to remove the tag qucikly?

**Comment by pjeby** [comment]
No.  If you want the long answer, please see my reasoning in issue #4 - the issue which is pinned at the top of the Issues page so that people don't open duplicates of it.  This issue was technically not a duplicate, since the goal is actually a simple search-and-replace.  Actually *removing* tags is a lot harder to do, outside of the file properties, since punctuation and formatting can be affected in all sorts of ways.

**Comment by Medullitus** [comment]
Thank you. It's surprising that additions that seem simple to us lead to such complicated situations. Unfortunately, search and replace plugins don't work properly. I want to delete them one by one, but except for one, all of them have the 'replace all' option. Dmitry Savosh's plugin is very successful. However, its hotkey feature doesn't work either.

**Comment by pjeby** [comment]
Since vaults are just files, you can also use any other multi-file search and replace, such as the one in VSCode.  Many text editors have the feature, and there are other tools like dnGrep.  So unless you're on mobile only, you aren't restricted to just using Obsidian plugins for the purpose.
