### ISSUE TITLE
"Failed to Load"

### ISSUE THREAD

**Issue by mattpackwood** [pjeby/tag-wrangler#134]
I am getting (consistently) "Failed to Load" errors, any thoughts / suggestions / insight?

Matt

**Comment by pjeby** [comment]
Plugin and Obsidian version?

**Comment by mattpackwood** [comment]
I am running v1.6.3 and plugin version 0.6.1

It seems to work in Sandbox (ugh).....

**Comment by pjeby** [comment]
Just so you're aware, Tag Wrangler doesn't have the word "Failed" in its code, so that must be a message from Obsidian or another plugin.  Have you checked the developer console (ctrl-shift-I) to see if there are any error messages?  There's likely more information there.

**Comment by mattpackwood** [comment]
I did not get a chance to access the developer console (I can't send that keyboard combination), but I removed all add-ons and reinstalled...  Seems to be "unbroken".

**Comment by pjeby** [comment]
It was probably a plugin ordering issue, then -- some plugins do stuff at startup that depends on the order of other plugins.  No way to know which one it was without the console though.  If you're on a Mac, it's probably cmd-shift-I, and might be in the app menu as "Open Developer Tools" or something like that.  (Just for future reference if you have this again or other plugin issues.)
