### ISSUE TITLE
Tag pane or tag view?

### ISSUE THREAD

**Issue by brandondrew** [pjeby/tag-wrangler#135]
The README says 

> Also, make sure that you have enabled the "Tag Pane" plugin, in the "Core Plugins" section of your vault's configuration. This plugin adds a context menu to the pane provided by that plugin, and does not have any UI of its own.

I don't see anything called "Tag Pane", but I do see "Tag View".  I'm about 95% confident that "Tag View" is intended and perhaps Obsidian changed its terminology recently.  But there is a small chance that "Tag Pane" was changed to something else that no longer has "Tag" in the name and which I therefore couldn't find. 

In either case, it would be helpful if the README could be corrected. Thanks!

**Comment by pjeby** [comment]
Yes, that's an Obsidian change since TW was created.  I've updated the README accordingly..
