### ISSUE TITLE
Dark Mode obscures input text field

### ISSUE THREAD

**Issue by adxsoft** [pjeby/tag-wrangler#14]
I have Obsidian set to Dark Mode. When I right click on a tag and choose Rename the popup for the new name is showing black text in a dark gray box
![Screen Shot 2021-04-24 at 1 22 51 pm](https://user-images.githubusercontent.com/24862237/115945700-36a07300-a500-11eb-91c3-6fc90c0323cd.png)

**Comment by pjeby** [comment]
This should be fixed in 0.4.2, which now uses the theme color variables for text and backgrounds.  Thanks for the report!
