### ISSUE TITLE
Backlinks are missing 

### ISSUE THREAD

**Issue by Marcel7Be4** [pjeby/tag-wrangler#141]
Maybe it's due to me using properties. But, after creating a tag page, there are no unlinked mentions in my backlinks.

I use a nested tag "Philosophy/Metaphysics" and have exactly 12 other notes with that tag. However, none show up in the unlinked mentions for the tag page.

**Comment by Marcel7Be4** [comment]
> You can just add another alias to the tag page without the `#` though, and that should get it working for those instances as well.

Just did that. Unfortunately, it doesn't seem to work.

**Comment by pjeby** [comment]
Are you seeing a zero next to "Unlinked Mentions"?  If not, click it.  If the zero shows (or some other number), and what you're looking for is not showing up, then the unlinked mentions search doesn't work on properties, and you'll need to do them manually at the moment.

**Comment by Marcel7Be4** [comment]
> Are you seeing a zero next to "Unlinked Mentions"?  

Yes. There is a zero. 

I've also tried it with tags that are not nested and have a similar issue. In those cases, the only unlinked mentions are notes that have the alias in the body—for example, "history"—but none of the notes actually tagged with history ever show up.

**Comment by pjeby** [comment]
And by "actually tagged" you mean in the tags *property*, not has `#history` in the body?

**Comment by Marcel7Be4** [comment]
Yes, exactly.

**Comment by pjeby** [comment]
Ok, yeah, that's not going to work, even though in theory it should.  In practice, Obsidian's "Unlinked Mentions" only searches the body because at the time they didn't support creating links in properties.  And if even if it did work it wouldn't work properly for the tags field since links aren't supported there.  You'll need to use some other methods for this I'm afraid.

**Comment by Marcel7Be4** [comment]
Understood. I was hoping to use tag pages to create MOCs, but I'll think of something else. Thank you for your time, sir.
