### ISSUE TITLE
[feature request] Add "Tag search" option in "Tag view" pan

### ISSUE THREAD

**Issue by craziedde** [pjeby/tag-wrangler#145]
Good afternoon,

Feature request in the screenshot below:
![image](https://github.com/user-attachments/assets/ba5f09e4-3497-44df-93ad-9a0e3a4645a0)

PS: I think you could "borrow" a sample code from "Outline" search pan

Thank you,

@craziedde

**Comment by pjeby** [comment]
As mentioned in #35 , I don't have any current plans to add this.

You probably want to add your support to this feature request for Obsidian itself: https://forum.obsidian.md/t/search-filter-box-in-tag-pane/11890/20
