### ISSUE TITLE
Autocomplete no longer works

### ISSUE THREAD

**Issue by yalcinarsan** [pjeby/tag-wrangler#15]
I can no longer see suggestions (for existing tags) when renaming a tag as I start typing. Is this a bug or a change in behavior?

**Comment by pjeby** [comment]
Tag Wrangler has never had such a feature; perhaps you are confusing it with something else?

**Comment by yalcinarsan** [comment]
My apologies then... Maybe I dreamed it to be the case? :)

**Comment by pjeby** [comment]
Who can say for certain?  :)
