### ISSUE TITLE
search tags in tag-pane not from tag-pane

### ISSUE THREAD

**Issue by PSEUDO-SAPPHO** [pjeby/tag-wrangler#16]
is:open label:enhancement  it's hard to find tags in tag-pane. I would love to search first in  tag-pane for mother of child-tags THEN OPERATE SEARCHING for nested tags.

**Comment by pjeby** [comment]
Sorry, but this is something you would need to request from the Obsidian core developers, as it's not something this plugin can add from the outside.  (It would require changing the inner workings of the tag pane to be able to filter the tags, whereas this plugin's menu is just looking at the HTML to get tag names and then doing something with that.)
