### ISSUE TITLE
Please add an option to collapse top-level tags without children

### ISSUE THREAD

**Issue by thomasvs** [pjeby/tag-wrangler#17]
Use case: I have a few curated tag hierarchies (c/ for context, l/ for location, p/ for person) and a lot of ad hoc tags with no structure or hierarchy.

It would be great if it was possible to collect all top-level leaf tags into one expandable bucket, at the same level as all of the other top-level non-leaf tags.

**Comment by pjeby** [comment]
It would be great, but it's not something this plugin can do, as it would depend on the functionality for such a thing being present in Obsidian itself.
