### ISSUE TITLE
Issue editing YAML tags

### ISSUE THREAD

**Issue by mlaetitia** [pjeby/tag-wrangler#18]
First of all - thanks for this great plugin! It's pretty cool and works amazingly!

I am not sure whether this is a user error or an actual bug, so I decided to log it anyway - feel free to just close it if it doesn't make sense.

I wanted to use a note Metadata to add notes. Using metadata, the only way for a tag to be added to the tags list is to add it as:

```
---
tags: mytag
---
```

As you can see, it cannot have the `#` at least on my end. I like this though, as it is the only way to actually show the tag in the note which I find useful.

However, when built this way, the tag renaming doesn't work:

<img width="1113" alt="tag-wrangler 1" src="https://user-images.githubusercontent.com/30905719/124675394-8615fe80-deb4-11eb-9496-dac420e31acf.png">
<img width="547" alt="tag-wrangler 2" src="https://user-images.githubusercontent.com/30905719/124675397-87dfc200-deb4-11eb-835c-15486dcd14da.png">
<img width="1123" alt="tag-wrangler 3" src="https://user-images.githubusercontent.com/30905719/124675399-88785880-deb4-11eb-8160-9806ce31da28.png">

**Comment by pjeby** [comment]
I used the exact same text:

```markdown
---
tags: on/wellbeing
---
```

And renamed it to on/wellbeing2 and it worked just fine.

So i you switch to preview mode, do the tags in the metadata for your test file show as `#on/wellbeing`?

**Comment by pjeby** [comment]
Also, since somebody else has reported a similar problem with YAML today, can I ask what version of Obsidian you are on?

**Comment by mlaetitia** [comment]
Sure! I am in v0.12.9 (the latest, I believe)

This is what it looks like in Preview:

I just tested with the community plugins inactive (except for tag-wrangler) and the same issue occurs.

**Comment by pjeby** [comment]
I am unable to reproduce this on 0.12.9 either.  Can you please paste a copy of the content of your file (inside triple backquotes), or better still, create a note with *only* the following text in it:

```yaml
---
tags: test/me
---
```

And see if the error occurs.  (Also, I'm assuming you're using the latest version of the plugin; if not, upgrade to match the version I'm testing with.)

**Comment by mlaetitia** [comment]
I think I got it!
The issue happens when the YAML metadata area does not start in the very first line of the file.
In my case, i somehow added a blank line before the start of metadata and this caused the error:

![Screen Capture on 2021-07-07 at 21-53-39](https://user-images.githubusercontent.com/30905719/124827527-0a788800-df6e-11eb-91f8-d0294dabda70.gif)

**Comment by pjeby** [comment]
I've updated the plugin to ignore blank lines above the front matter, so you shouldn't have this problem again.  Thanks for reporting the issue.

**Comment by mlaetitia** [comment]
It works !! :) thanks for the quick fix 🚀
