### ISSUE TITLE
Renaming and merging doesn't work

### ISSUE THREAD

**Issue by dummifiedme** [pjeby/tag-wrangler#19]
Renaming and merging a tag doesn't update anything. 

#### EDIT:
**Found it:** It doesn't update the meta tags!!!!!!
Please fix?

![image](https://user-images.githubusercontent.com/68785729/124704007-fa7e8b00-df10-11eb-9fd4-86f0384ea481.png)
![image](https://user-images.githubusercontent.com/68785729/124704027-036f5c80-df11-11eb-91f0-e2552df9a2d9.png)
![image](https://user-images.githubusercontent.com/68785729/124704045-09653d80-df11-11eb-9673-1b763ec99435.png)
![image](https://user-images.githubusercontent.com/68785729/124704059-0f5b1e80-df11-11eb-95c3-1d5393e56f5b.png)
``

**Comment by pjeby** [comment]
What version of Obsidian are you on?

**Comment by dummifiedme** [comment]
> What version of Obsidian are you on?

Obsidian 0.12.5

**Comment by pjeby** [comment]
That's the same version I'm on and mine works.  Can you paste a sample file that gets ignored?  (The smaller the better, and put it in a code block (three backticks on a line before and after).

**Comment by pjeby** [comment]
Also, if your files have whitespace above the opening `---` line, update to the 0.4.5 version of the plugin.  Whitespace is not technically allowed above the frontmatter in most Markdown implementations, but Obsidian apparently allows it.

**Comment by dummifiedme** [comment]
> 
> 
> That's the same version I'm on and mine works. Can you paste a sample file that gets ignored? (The smaller the better, and put it in a code block (three backticks on a line before and after).

I tried to find a suitable example, and wasn't having any issue. I had solved my previous problem by using regex in VS Code. But today, I tried changing one more tag and it threw an error initially relating to duplication of meta fields. Upon fixing those 2 notes, it went on to change the tags as expected but could only change 9 out of a total 21. Rest were still unchanged,

I am attaching a screenshot of how that note looks. Both these notes were amongst those which weren't modified upon repeated attempts. (Tag in question is `#Polity`)

![image](https://user-images.githubusercontent.com/68785729/124947608-9a313b80-e02d-11eb-8b1a-9427ac0e5bec.png)
![image](https://user-images.githubusercontent.com/68785729/124947670-ab7a4800-e02d-11eb-84d3-1a2644c4bad0.png)

**Comment by pjeby** [comment]
Please paste the note text -- I can't copy text from a screenshot.  (For example, the note picture you posted looks like it has a tag with spaces in it, but Obsidian tags can't have spaces in them, so I assume there are special characters or non-standard spaces involved somehow.)

As I requested yesterday:

> Can you paste a sample file that gets ignored? (The smaller the better, and put it in a code block (three backticks on a line before and after).

**Comment by dummifiedme** [comment]
> Please paste the note text -- I can't copy text from a screenshot. 
Sure.
```
---
title: A K Gopalan Case
source:
date: 2021-05-31 15:03
aliases: [ ]
ankideck: UPSC::GS2
tags: 📝/🌱 Polity GS2
---

Category:: [[+ Discussion]]

---

# A K Gopalan Case
- The petitioner [[AK Gopalan]] appealed to examine the **validity of the preventive detention law** brought by the government of Pandit Nehru, the law to be interpreted in the light of concept of liberty given in the preamble.
- Supreme court **didn't** accept Preamble as a guiding star in the interpretation of the constitution.

```


> (For example, the note picture you posted looks like it has a tag with spaces in it, but Obsidian tags can't have spaces in them, so I assume there are special characters or non-standard spaces involved somehow.)

They are separate tags. And obsidian did identify them. 
![image](https://user-images.githubusercontent.com/68785729/124953441-c9967700-e032-11eb-8ad0-bdc8dacf948d.png)

I used to have another notaion for tags as `tags: [ tag1, tag2 ], but later dropped it since the way in the above code works well too and it helps me keep my ANKI tags in sync with the note tag. (else anki identifies `[tag` as a tag too. 

If that is the problem, I can maybe live with that.

**Comment by pjeby** [comment]
Ah.  Tag Wrangler doesn't currently support space-separated tags; there have to be commas between them, even if it is a YAML string rather than a list.  It looks like this is something that's changed in Obsidian recently, as when I wrote Tag Wrangler the commas were definitely required.

I've updated Tag Wrangler 0.4.6 to support space-separated tags in front matter.

**Comment by dummifiedme** [comment]
Thanks a lot! :)
