### ISSUE TITLE
Bug: Not compatible with dataview plugin

### ISSUE THREAD

**Issue by bhickta** [pjeby/tag-wrangler#20]
* Whenever tags are renamed in [tag-wrangler](https://github.com/pjeby/tag-wrangler/) plugin, the tags mentioned in [dataview](https://github.com/blacksmithgu/obsidian-dataview) block is not appended
* Eg
  * If i change Tag name #Tag1 with #Tag2, change will reflect everywhere in vault except in dataview block
  \`\`\`dataview
     list
     from #tag1(not changed to #tag2)
   \`\`\`

**Comment by pjeby** [comment]
Tag Wrangler only changes tags recognized by Obsidian, and Obsidian does not recognize tags inside code blocks.

**Comment by bhickta** [comment]
Sir kindly see the reply from dataview plugin manager

This is not something I can fix from my side - I suspect the reason for this is that `tag-wrangler` uses the Obsidian metadata for where tags are, which does _not_ include any tags that show up in codeblocks. `tag-wrangler` will need to add support for changing tags inside of dataview codeblocks (or some other workaround) to work properly.

Have you filed an issue on their tracker? You can tag me in it.

_Originally posted by @blacksmithgu in https://github.com/blacksmithgu/obsidian-dataview/issues/328#issuecomment-879612957_

**Comment by pjeby** [comment]
I could probably add a hook of some kind for plugins to report the position of non-Obsidian tags (e.g. ones in codeblocks) for Tag Wrangler to rename, but I have no plans to implement any parsing of codeblocks.  So if @blacksmithgu 1) has some way to track which codeblocks in what files reference tags and 2) is willing to expose that info to Tag Wrangler via an event handler, then I'd be willing to work out an interface for that.

On my end, the requirement would be to have a list of tag names and their absolute start positions within each file, obtained synchronously in response to an event.

**Comment by bhickta** [comment]
Thanks for just great support sir..
