### ISSUE TITLE
Renaming tags when braces used in front matter causes unexpected behaviour

### ISSUE THREAD

**Issue by jacrify** [pjeby/tag-wrangler#23]
I have the following front matter:
```
---
title: Awaken the Giant Within
tags: ln/1☀️ book
author: [[Tony Robbins]]
---
```

Renaming tag "ln" to "l" using the tag pane results in the following- note spaces on author line.
```
---
title: Awaken the Giant Within
tags: l/1☀️ book
author: [ [ Tony Robbins ] ]
---
```

**Comment by pjeby** [comment]
See https://github.com/pjeby/tag-wrangler#front-matter -- whitespace in frontmatter is not guaranteed to remain the same after renaming tags.  The value of the frontmatter hasn't been changed here, only the spacing.  (In YAML, `[ [ x ] ]` and `[[x]]` are both the same as `[["x"]]` in JSON: that is, they are all ways of saying "a list containing a list containing a string".)

Plugins that conform to the YAML spec should not be affected by the change in whitespace.

**Comment by jacrify** [comment]
Yeah I read the linked limitation before filing. However the case I’m
talking about isn’t covered there. The link states:

However, due to limitations of the parser involved, some whitespace in the
front matter may be removed or reduced.

I’m not seeing whitespace *removed*, but introduced, and as part of a value
that doesn’t contain tags.  It’s pretty destructive.  I’m guessing you are
parsing and rewriting the whole yaml block and this is why?

Is there a way I can put [[]] links in my yaml that won’t be impacted by
this?

Love the plug-in otherwise.

**Comment by pjeby** [comment]
Yes, it has to be parsed and rewritten.  The whitespace changes are introduced by the yaml parser.

As for not having links impacted, plugins that look for links as nested lists will not care about the extra spaces: the value of the field is not actually being changed, only its formatting.  Plugins that use the parsed metadata will not care about the extra spaces, and Obsidian itself has no concept of links in frontmatter.

If the whitespace bothers you for some reason, and you're using plugin(s) that support string links (like dataView does), you can simply use `"[[whatever]]"` (i.e. put the entire link in quotes).
