### ISSUE TITLE
Feature Request: Recognize tags inside code blocks

### ISSUE THREAD

**Issue by bhickta** [pjeby/tag-wrangler#24]
## Use case
* Query
  * Whenever query a line/block using #tag as parameter/input - making dynamic notes with common database
* Dataview
 * To list out all notes using #tag as parameter/input

## Why only tag-wangler
* giving a tag to a block/note is dynamic and spontaneous but later one needs to cleanup tags and tag-wrangler provide exactly this functionaly
* but if it's not able to provide tag recognition in code-blocks, it creates inconsistency in notemaking

## A Humble request
* Though your plugin is great with little room to imporvement, atleast i think so, but if possible, please add the following functionality

## Related issue
#20

**Comment by pjeby** [comment]
As I mentioned in #20, the only way tags will be parsed in code blocks is if the developers of other plugins are willing to do the parsing to identify tag locations, and Tag Wrangler will then handle making the changes.
