### ISSUE TITLE
respect existing yaml format

### ISSUE THREAD

**Issue by sigmoid-azoth** [pjeby/tag-wrangler#26]
Hi there,

I've noticed that number of my vault files have had their yaml format changed and after testing, it looks like the culprit is your plugin.

before tag rename:
![image](https://user-images.githubusercontent.com/87744778/129104388-470edff5-8957-4c45-89b8-acad0f9d1af5.png)

after tag rename:
![image](https://user-images.githubusercontent.com/87744778/129104446-293154a7-1e01-4012-9074-c51ee832812c.png)

could you please modify the functionality so that preexisting whitespace is preserved and `null` is not added to yaml keys without vaules?

**Comment by sigmoid-azoth** [comment]
Additionally, I have observed that notes affected by the whitespace/`null` change sometimes have their yaml collections reformatted from single-line to multi-line but I have not been able to reproduce this consistently.

from:
![image](https://user-images.githubusercontent.com/87744778/129106205-ca73795a-3ebf-4037-935d-cc926441ab0d.png)

to:
![image](https://user-images.githubusercontent.com/87744778/129106241-94ca9888-f05d-4a21-8977-99be1aa47662.png)

If tag-wrangler is the cause, I would like to request that existing collection formats remain as specified in the source note

**Comment by pjeby** [comment]
Unfortunately, this is entirely dependent upon the availability of a Javascript library capable of editing YAML in place without making these types of changes.  Of all the libraries I have tried, the one I'm currently using is actually the *best* in terms of maintaining formatting while still guaranteeing valid YAML post-editing.  Other libraries exist which do a better job of minimal editing, but when they do fail, they fail by changing the *semantics* of the YAML rather than its formatting.

I wasn't aware of these specific formatting issues, and I expect at some point I will investigate whether I can get the upstream library to fix them, but I would not hold out much hope in the short run for this changing any time soon.

**Comment by sigmoid-azoth** [comment]
Understood. I figured it would be difficult since yaml writes aren't currently a part of the obsidian api and you're relying on a third party library, but thank you for looking into it and for your efforts in creating this helpful plugin

**Comment by birgittealstrom** [comment]
Thank you @sigmoid-azoth for creating this feature request as I was looking for help regarding exactly the same issues.

@pjeby : Thank you for building this very important plugin. Any news reg. this feature request? I would really prefer the existing YAML format to be respeced, when renaming tags.

In the meantime maybe it is an idea to update the documentation regarding this known issue, as I could only find information stating the plugin would maybe delete some whitespace, but not regarding adding whitespace or null or rearranging.

**Comment by pjeby** [comment]
That'd probably be a good idea (to update the documentation on this).

Currently, there still exists -- as far as I can tell -- NO library in ANY language (I checked JS, TS, Python, Dart, and Go libs) that will preserve 100% of comments, indentation, and semantics, and the library I'm currently using is the best available that can be used directly in Obsidian.  (And quite possibly the best available, period.)

It's likely *possible* to use some of that library's features to do a more surgical edit, especially in the case of Tag Wrangler, which does not need to add or remove items, only edit some string values in-place.  But actually *implementing* the code for that would likely be a multi-weekend project for me and not something I'm willing to commit to a schedule of at this time.  If somebody else wants to tackle this and implement a PR, I'd love to hear from them regarding their plans before they start, so we can make sure that it'll handle all the known edge cases.

In the meantime, I will update the documentation, and have pinned this issue so it's more prominent.

**Comment by pjeby** [comment]
This is now fixed in 0.4.7 -- turns out it was only a one-weekend project, due to some recent changes in the underlying library.  There are still some limitations, though, for tags using block scalars or YAML aliases, but that would not affect any of the YAML shown in this issue.

**Comment by birgittealstrom** [comment]
Thank you so much, @pjeby, for taking the time updating the plugin. It is highly appreciated 🙏 The update works smoothly.
