### ISSUE TITLE
[FEAT] ignore specific folders in the setting tab

### ISSUE THREAD

**Issue by yo-goto** [pjeby/tag-wrangler#29]
Hi, pjeby.
Please consider adding a feature to ignore specific folders in the setting tab. 
My vault has various folders like official documents "Typescript Deep dive" which I cloned from Github, many Readme files or blog markdown folder to generate static site by Hugo and so on. When trying to rename tags, it may trigger to unintentionally change file contents in those folders. These folders have markdown files which I don't know or I don't create by myself.

And also, there may be important documents we don't want to change **at all**. In order to protect those documents from unintentionally change, I think this feature is important.

Thanks.

**Comment by pjeby** [comment]
My suggestion would be for you to use VSCode: there is a VSCode plugin for Obsidian that opens the vault as a VSCode project, all you need to do is configure the project to exclude the folders from search, then use global search-and-replace.  (VSCode stores its configuration in a .vscode directory under the vault, that Obsidian will ignore.)  Note that you should also exclude the `.obsidian` folder from VSCode's search, so it will not alter Obsidian's configuration or any plugin code.

**Comment by yo-goto** [comment]
It worked well. Thank you!
