### ISSUE TITLE
Adding support for mobile devices?

### ISSUE THREAD

**Issue by claremacrae** [pjeby/tag-wrangler#31]
Hello, and thank you for this very helpful plugin.

I see that this plugin is currently marked as `"isDesktopOnly": true`.

Is there any possibility of it being changed to support mobiles, please?

Is it known what needs to be done, in case someone else (maybe me) might be able to contribute with a PR?

**Comment by pjeby** [comment]
I don't use Obsidian mobile so I don't have an easy way to test it, or to fix it if it breaks.  If you want to, however, you can always copy it to your mobile device after changing the manifest to say false.  If it works, then great!

Just out of curiosity, what part of this were you interested in using on mobile?

**Comment by claremacrae** [comment]
@pjeby Thank you - thank makes perfect sense.

Once I've managed to get syncing of plugins from desktop to mobile, I will definitely do that.

I'll be using my iPad - with keyboard - in Obsidian.

It's early days, as I'm still at the "folders vs tags" stage, on a few thousand files imported from Dropbox...

**Comment by pjeby** [comment]
Alright, well let me know if it works for you.
