### ISSUE TITLE
[Feature] Search tags in tag pane

### ISSUE THREAD

**Issue by cogscides** [pjeby/tag-wrangler#35]
Would be good to have feature to search in your tag pane.
As for person who started using tags a lot I miss feature in obsidian that allow me to search in my already created tag list

**Comment by pjeby** [comment]
You should probably request this as an Obsidian feature, as I don't have any current plans to extend the plugin in this direction.

**Comment by musicleaf** [comment]
在obsidian上搜索特定标签的时候, 能定位到相应位置也行, 方便修改标签的名称
