### ISSUE TITLE
Alt-clicking a tag in the tag pane to open an existing tag page always opens the tag page in editing view

### ISSUE THREAD

**Issue by Alienchisel** [pjeby/tag-wrangler#39]
Expected behavior: Alt-clicking a tag in the tag pane to open an existing tag page opens the tag page in editing view if editing view is the default new pane view or in reading view if that's the default, as per the Obsidian general editor settings. 

Basically, I just want the tag pages to open in reading view.

Does this make sense? Maybe I'm missing something.

Thank you

**Comment by pjeby** [comment]
This should be fixed in 0.5.1 - it was always setting editing view for the benefit of new tag pages, and I didn't notice because I don't really use reading view except for notes I stash in my sidebars.  Let me know if you still have problems with it.
