### ISSUE TITLE
Tag page page links are not recognized as tags

### ISSUE THREAD

**Issue by zacharyw** [pjeby/tag-wrangler#42]
This could be some misunderstanding or user error on my part, but I'm trying to figure out how to implement tag pages in my workflow.

This line from the documentation:
> Specifically, viewing a tag page's "unlinked mentions" will show you all the locations where the tag was used and "link" buttons you can use to convert them to page links. (Converting page links to tags requires hand editing.)

Makes it seem to me that the intended workflow is to create a tag like "#tag", then right click it in the tag pane and convert it to a tag page. Then, I can go to unlinked backlinks on the tag page, and click the "link" button on every unlinked instance... this replaces the tag on those notes with "#[[tag]]".

I replaced a few like this before realizing that "#[[tag]]" tags no longer show up in the tag pane and you can't search for them like "tag:#tag" or even "tag:#[[tag]]".

I like the idea of using tag pages to get the best of both worlds from tags and pages, but I'm struggling on how to get them to function as tags and also proper backlinks.

**Comment by pjeby** [comment]
You only need to click the "link" button if you are intending to *migrate* (i.e. convert) the tags to links.  If you want to keep them as tags, don't do that - just leave them as tags.  The "best of both worlds" here is that you get them as dedicated tags but still can hover or jump to the actual page.

So, tag pages mean you can use links or you can use tags or you can even use both, but any individual reference is either a link or a tag.

**Comment by zacharyw** [comment]
@pjeby Ahh, I see, thanks for the explanation.

One issue I wanted to mention if you aren't already aware - the ability to hover/click on a tag and go to the tag page (instead of running a search for the tag) doesn't seem to work within Notes when using the "live preview" mode of editing mode.

**Comment by pjeby** [comment]
You have to alt-click a tag to open the tag page, no matter where the tag appears.  Hovering is controlled by the page preview settings for the appropriate plugin or view.
