### ISSUE TITLE
tag-wrangler hijacks button style

### ISSUE THREAD

**Issue by NeighNeighNeigh** [pjeby/tag-wrangler#43]
When I have tag wrangler activated, it injects the following css into obsidian:
```
button {
    font-family: Ubuntu, Arial, sans-serif;
}
```
This makes some of Obsidians buttons use the Ubuntu font family, which is undesirable

**Comment by pjeby** [comment]
This should be fixed in 0.5.2, it's a problem with the CSS from one of the libraries I'm using.
