### ISSUE TITLE
FEATURE REQUEST: Automatic creation of tag pages

### ISSUE THREAD

**Issue by isle9** [pjeby/tag-wrangler#45]
It would be nice if there was an option to create tag pages automatically.

**Comment by pjeby** [comment]
I don't understand what that means.  They are already created automatically when you select the menu option?

If you mean creating them whenever tags created, that wouldn't work very well at all.  If your timing is even slightly off when you type a tag, Obsidian will create (and then delete) various tags that are shorter versions of the same tag.  And if you then undo your typing (or fix a misspelling), you'll end up with a bunch of extra tag pages permanently enshrining their temporary existence, until you track down and delete those tag pages manually.  So if you mean "create tags for every page automatically when tags are created", that would likely be more trouble than it's worth.

**Comment by isle9** [comment]
Hmm, that does seem like a hassle. What about giving us an option to open tag panes when normally clicking on them instead of using alt click and  changing the alt click to open them in Obsidian search?

**Comment by pjeby** [comment]
That would require more complex overriding of Obsidian's built-in behavior, making it more fragile.  It'd also require adding options, which I prefer not to include in my plugins where possible.

**Comment by isle9** [comment]
How about using shift click instead of alt click? It seems like shift clicking doesn't do anything currently.

**Comment by pjeby** [comment]
See previous comment regarding the need to add options.
