### ISSUE TITLE
How can I get  the text of all the tags?

### ISSUE THREAD

**Issue by asasn** [pjeby/tag-wrangler#46]
I want to paste it into a document for easy display in the relational graph.

Copy text Just like
```#tag1 #tag2 #tag3 #tag4 ...```

**Comment by pjeby** [comment]
One way to do this is to use the QuickAdd plugin.  Add a "Capture" choice, configure it to "Capture to Active File" and "Capture Format".  In the format box, put the following:

~~~markdown
```js quickadd
return Object.keys(app.metadataCache.getTags()).sort().join('\n')+'\n'
```
~~~

You can then insert the tag list by triggering the action you configured.  (E.g. by issuing the quick add command and picking it from the list, or by assigning it a keyboard shortcut.

There are probably other ways to do this, but this is likely the simplest one by far.

**Comment by pjeby** [comment]
Oh, if you want all the tags on the same line, replace the bits that say `'\n'` with `' '` -- I wrote the above thinking you wanted them one per line.

**Comment by asasn** [comment]
I get it, thanks.
