### ISSUE TITLE
Smart Random Note do not work

### ISSUE THREAD

**Issue by wuzhen97** [pjeby/tag-wrangler#48]
Awesome plug-in！
when I use Smart Random Note, there are the following errors:

![notice](https://user-images.githubusercontent.com/61906420/178401799-3f07353e-e83f-4bf4-8c1b-5dc1f0872cbf.png)

![metadata](https://user-images.githubusercontent.com/61906420/178401946-372788c7-c43b-4232-8b8b-457bbd016b5a.png)

Please help me, thanks.

**Comment by pjeby** [comment]
If you disable this plugin, does Smart Random Note not give you the error?

**Comment by wuzhen97** [comment]
> If you disable this plugin, does Smart Random Note not give you the error?

Even if I don't disable this plugin, Smart Random  Note still works normally for selected tag：

![image](https://user-images.githubusercontent.com/61906420/178444570-d5b5a347-c27d-4b24-aa68-d906654269cf.png)

![image](https://user-images.githubusercontent.com/61906420/178444586-4c224c08-104b-4d3b-8950-b1bb15cd5c0a.png)

**but it doesn't work in the tag panel：**

![image](https://user-images.githubusercontent.com/61906420/178444798-45e09356-893c-47b7-bf06-f0dd7cbd280b.png)

![image](https://user-images.githubusercontent.com/61906420/178444906-8e8f91e8-7e2c-49af-931e-448c6f9556e8.png)

**Looking forward to your reply!**

**Comment by pjeby** [comment]
It looks like 0.2.1 of Smart Random Note changed its API, such that Tag Wrangler doesn't work with it any more.  (I'm on an older version so didn't see an issue.)  Tag Wrangler 0.5.3 fixes the problem, so you should just be able to update it.
