### ISSUE TITLE
Template for tag pages

### ISSUE THREAD

**Issue by 23tux** [pjeby/tag-wrangler#49]
Hi,

1. If I understand correctly, a "tag page" created by the plugin does not include a list of notes and I'm responsible to create a dataview of it. Am I right?
2. If so, is there a way to provide a default template when creating tag pages?
3. Can I reference the current `Aliases: ["#foobar"]` in my dataview? This doesn't work:

````
---
Aliases: [ "#foobar" ]
---

```dataview
table from aliases[0]
```
````

Error:
```
Dataview: Error: 
-- PARSING FAILED --------------------------------------------------

> 1 | table from aliases[0]
    |            ^

Expected one of the following: 

'!', '(', '-', 'csv(', 'outgoing(', file link, string, tag ('#hello/stuff')
```

**Comment by pjeby** [comment]
1. Correct
2. No.  But you can create a template using any of several plugins (including Obsidian's built-in templating) and inject it with a few keystrokes.
3. Not so far as I know.  I would suggest that instead you use one of the templating plugins that allows you to insert variables at multiple places in a template, and prompts you for the variable.  Then you could make a template that inserts the same tag as both an alias and in the dataview part, so you can just use that template to create your tag pages instead.  (The page does not have to be created by Tag Wrangler -- any page with a tag as a frontmatter alias will be recognized as a tag page.)

**Comment by 23tux** [comment]
Thanks for the answer! I've managed to get No. 3 working with dataview and it's JS syntax:

````
```dataviewjs
let query = `TABLE "#" + join(sort(tags), " #") AS Tags, file.mtime FROM ${dv.current().file.aliases.join(" OR ")} SORT file.ctime desc`;
dv.execute(query);
```
````

**Comment by Heiss** [comment]
Hey,

@pjeby wrote:
> No. But you can create a template using any of several plugins (including Obsidian's built-in templating) and inject it with a few keystrokes.

why isn`t there any automatic for this? Is this hard to implement?
A lot of other plugins support such kind of template using and would be super helpful to work with tag pages.

**Comment by pjeby** [comment]
Exactly: a lot of plugins support creating notes from templates already, so no reason to duplicate the functionality here.  That way, you can use whatever templating tool you like most.  In the simplest case, you can use Obsidian's built-in templates, or you can use an advanced tool like QuickAdd or Templater to script something fancy and do whatever you need with a single keystroke.  These options are far more customizable than anything that Tag Wrangler could add, and would not require you to learn yet another template syntax if you already have one you like.

**Comment by tophee** [comment]
see also #76
