### ISSUE TITLE
Expand/Collapse only seems to work for 1st level tags

### ISSUE THREAD

**Issue by nixsee** [pjeby/tag-wrangler#5]
Activating this command on 2nd and 3rd level tags does nothing

**Comment by pjeby** [comment]
Fixed in 0.2.6.  Thanks for reporting!

**Comment by nixsee** [comment]
Thanks for the quick update! However, it only seems to collapse/expand 2nd/3rd/etc... level tags within the same 1st level nest. Not sure how it is meant to work, but I would prefer it to be applied to all tags in the browser.

**Comment by pjeby** [comment]
That's how it's meant to work, i.e. closing siblings.  I'll keep the feedback in mind for future versions, though.
