### ISSUE TITLE
[BUG] Can't use `<esc>` to switch Vim's `NORMAL` mode after right-click tag item

### ISSUE THREAD

**Issue by Deeperand** [pjeby/tag-wrangler#53]
# Issue Description
## Steps to reproduce
1. enable vim mode in obsidian and `tag-wrangler` plugin
2. enter insert mode
3. open tag pane by `Tags: Show tags`
4. `right-click` arbitrary tag item to open the pop-menu provided by `tag-wrangler`

## Expected result
The behavior of Vim mode should won't be effected

## Actual result
After the `right-click` operation, when I edit a file, can't use `<esc>` to enter Vim's `NORMAL` mode anymore unless I restart Obsidian. I also tried to disable `tag-wrangler` without relaunch Obsidian but it seems doesn't work. However, I can still use `<C-c>` or `<C-[>` to enter `NORMAL` mode.

In addition, the problem  won't reproduce when open a pop-menu at other sidebar-interface.

## Environment
- system: `macOS Monterey 12.6`
- Obsidian version: `v1.0.0`
- `tag-wrangler` version: `0.5.3`
- enabled core plugins
	- "file-explorer",
	- "global-search",
	- "switcher",
	- "graph",
	- "backlink",
	- "outgoing-link",
	- "tag-pane",
	- "page-preview",
	- "daily-notes",
	- "templates",
	- "note-composer",
	- "command-palette",
	- "editor-status",
	- "starred",
	- "outline",
	- "word-count",
	- "file-recovery"
- enabled community plugins
	- "tag-wrangler"

**Comment by pjeby** [comment]
Does this happen with right-clicking any sidebar panes other than the tag pane?

**Comment by Deeperand** [comment]
> Does this happen with right-clicking any sidebar panes other than the tag pane?

No, this only happen when I `right-click` the tag pane and with plugin `tag-wranglar` enabled. I've tried `rightl-clikc` sidebar pane such as `Files`, `Search`, `Stared`, `Backlinks`, `Calendar`(provided by plugin `Calendar`), but both of them won't effect the behavior of `<ESC>` key for `vim-mode`.

**Comment by pjeby** [comment]
What happens if you right-click one of those other panes *after* right-clicking the tag pane?

**Comment by Deeperand** [comment]
> What happens if you right-click one of those other panes _after_ right-clicking the tag pane?

It seems nothing special happen for other panes. For example, I can create/delete file or folder at the pane of `File` as usual.

**Comment by pjeby** [comment]
Try version 0.5.4 of this plugin; I've removed the special handling that once existed for the escape key.

**Comment by Deeperand** [comment]
> Try version 0.5.4 of this plugin; I've removed the special handling that once existed for the escape key.

The problem is solved by 0.5.4, very thanks for your quickly update!
