### ISSUE TITLE
Mobile compatibility

### ISSUE THREAD

**Issue by elight** [pjeby/tag-wrangler#55]
I *love* this plugin. I live by tagging.

I also love my iPad! It's more portable than my laptop!

I would be deeply grateful for tag-wrangler support on iPadOS. 🙏

**Comment by pjeby** [comment]
You can manually remove the "isDesktopOnly" line from manifest.json and try to use it that way.  Let me know if it actually works, as I don't use Obsidian on any mobile devices.

**Comment by pjeby** [comment]
Experimental mobile support is now available in Tag Wrangler 0.5.5.
