### ISSUE TITLE
Feature request:  drag a tag into a page!

### ISSUE THREAD

**Issue by wealthychef1** [pjeby/tag-wrangler#56]
I love Tag Wrangler, but I have a hard time tagging tasks, because of how carefully I have to place the tag and other weird reasons.  It would be incredibly helpful to have the ability to drag a tag from the list into my document!

**Comment by pjeby** [comment]
This ability to drag a tag and drop it into an editor pane as text is now available in Tag Wrangler 0.5.5.

**Comment by wealthychef1** [comment]
This is fantastic, works great, thanks.
