### ISSUE TITLE
Does not work on Android and IOS

### ISSUE THREAD

**Issue by racy2020** [pjeby/tag-wrangler#59]
Thank you for providing this plugin which helped me a lot. I have been using it on my PC for a long time. It works well on PC. But I found it did not work when I started using obsidian on my Android phone and iPad recently.

1. I modified the mainfest.json：`"isDesktopOnly": false`
2. run obsdian and turn on the plugin
3. when I hold any tag on tag-panel, the menu should pop up ( like right clicking on a PC ) , but it didn't.
4. so, I connect my Android phone to PC and run ADB
5. open the console and repeat step 3
6. the console output the message:
![df754fc9823569b3afc6b8b3](https://user-images.githubusercontent.com/70854078/200151072-4962244e-0af0-4891-8d75-46c0cfa62442.png)

Thank you again for providing this plugin. Can you make a bit change to enable it to support mobile?

**Comment by pjeby** [comment]
Try editing main.js and replacing setImmediate with setTimeout - see if it works then.  If so I will make a similar change in the official version.

**Comment by racy2020** [comment]
> Try editing main.js and replacing setImmediate with setTimeout - see if it works then. If so I will make a similar change in the official version.

Yes, it works on the mobile, it's great !

**Comment by pjeby** [comment]
Both changes are now in 0.5.5.  Let me know if any further issues occur.
