### ISSUE TITLE
[BUG] renaming tag throw error

### ISSUE THREAD

**Issue by Lynx3x** [pjeby/tag-wrangler#60]
error: TypeError: a.toLowerCase is not a function

1. create a file and write some tags in yaml like
```
---
tags: 
- sometag1
- sometag2
- 123
---
```
2. when it has a tag that only has number (actually it is not recognized as a tag, I just typed it accidently), and I do the rename command to `#sometag1`, then the console throw error `error: TypeError: a.toLowerCase is not a function`.

I don't konw whether it is a bug of Obsidian. If so, nevermind.

**Comment by pjeby** [comment]
This is a duplicate of #51 - Renaming produces TypeError: t.toLowerCase is not a function.  Please see there for more details.
