### ISSUE TITLE
[Feature Request] Cluster: show connections between tags

### ISSUE THREAD

**Issue by mikjailc** [pjeby/tag-wrangler#63]
Hello. Wondering if this FR is possible: when searching for a tag –or more– I'd like to have the option to see with which other tags it shares at least one note. 

With this option, for example, when clicking "#A" I could see that "#A" coexist or lives in the same space – i.e. share at least one note – with "#B", "#C" and "#D". A list is displayed with only the name of tags that are directly related, in this case the list would have "#B", "#C" and "#D". And when I click – maybe pressing a key– on another tag, already having selected a previous one, they cluster. For example, with "#A" and "#B" being selected, a list with the tags, if any, that coexist with "#A" and "#B" would be displayed. Finally, every time I do the cluster with at least more than one tag ("#A" + "#B"), I can see the titles of the notes in which those tags coexist.

Of course, the latter is already possible to some extent: searching "tag:#A tag:#B" shows the notes they share. And it's fantastic. But the previous steps I think they can't be replicated right now and are necessary, because I don't know, in advance, which tags coexist in the same space. That's what I'm asking for.

This is an option of Lüdecke's Zkn3:

![Captura de Pantalla 2022-12-14 a la(s) 21 14 38](https://user-images.githubusercontent.com/119732315/207756967-c79140c3-3dac-4e7f-83dc-09537d552c23.png)

Here, when selecting "Kontrolle", it shows, below, all the keywords –tags in Obsidian– with which it coexists in at least one note. And by selecting, below, "accountability", they cluster ("Kontrolle" + "accountability") and if I open the "accountability" tab I can see the keywords that coexist with those two keywords. On the board below are the notes they share ("Zettel: 1060"), just like the normal Obsidian search.

I hope this is not that crazy and you can consider expanding into that place.

Thanks and cheers!

**Comment by pjeby** [comment]
You probably want this plugin instead: https://github.com/alexobenauer/obsidian-tag-navigator

**Comment by pjeby** [comment]
(Oh, and the Tag Folder plugin has something similar, but not quite as easy to use.)
