### ISSUE TITLE
FR: New Tag Pages should have a default template

### ISSUE THREAD

**Issue by j-maffe** [pjeby/tag-wrangler#67]
So I've been playing around with the Tag Page and found it to be a lot more useful when it has a DataView query of all files that have that tag. This worked for me using DV and Templater:
```dataview
TABLE FROM <%tp.frontmatter.Aliases%>

```
Maybe you could include something like this by default or allow for a custom template to be inserted by the user (the same way Folder File does it)?
Awesome work!

**Comment by pjeby** [comment]
You can just create a template that inserts both the alias and the query, possibly prompting you to enter the tag to begin with.  You don't need Tag Wrangler to create the page for you -- it recognizes any page with the correct alias entry.

**Comment by j-maffe** [comment]
Ah yeah that's a good point! I'm still thinking what kind of content would be fit for the tag page.
