### ISSUE TITLE
FR: Alt-clicking Nested Tab should goto Parent Tab's Tab Page if Nested Tab doesn't have a Tab Page

### ISSUE THREAD

**Issue by Interpause** [pjeby/tag-wrangler#69]
I use nested tabs to organize some notes, for example: `#idea/product`, `#idea/social`, etc. I would like these to redirect to `#idea`'s tab page if they do not have their own tab page. Would this be useful?

**Comment by pjeby** [comment]
Any given note/page can be a tag page for any number of tags.  So you can just add the other tags (e.g. `#idea/product`) to the `#idea` note's aliases field (then remove them when you make a tag-specific page).

**Comment by Interpause** [comment]
Yeah I discovered that works. Still a bit manual if I decide I need a new subtag on the fly. But probably not worth the trouble and potential feature conflicts to implement.
