### ISSUE TITLE
FR: add ToC of tagged pages to tag page

### ISSUE THREAD

**Issue by tcoliver** [pjeby/tag-wrangler#71]
I would love to have a way to add a list of all tagged pages to a tag’s page. Ideally this list would be updated as new pages were tagged upon save.

**Comment by pjeby** [comment]
You can use the Dataview plugin for this - just put a `LIST FROM #tag` query in the tag page.  If you don't want to manually put a dataview query in each tag page, you can use a templating plugin to create your tag pages and insert both the alias and the dataview query.

**Comment by tcoliver** [comment]
Thanks for the reply! What you describe is actually what I am currently doing. What I am suggesting/requesting is more akin to what [Waypoint](https://github.com/IdreesInc/Waypoint) does in that it actually writes the markdown to the page and keeps it updated. That said, I fully understand that this request may be out of scope for what this plugin does. So, no worries if this is not in scope.

**Comment by pjeby** [comment]
Yeah, it sounds like a plugin for writing out dataviews or other queries would be a better choice for this.  (Especially since it could then be used for things besides this.)  And a feature like this is definitely out of scope for Tag Wrangler
