### ISSUE TITLE
Short and clean tag

### ISSUE THREAD

**Issue by yoghurtdewdew** [pjeby/tag-wrangler#72]
Allow to hide the display of the parent tags in the reading interface. When multiple levels are set, the tag will be very long

**Comment by pjeby** [comment]
You would need to request this as an Obsidian core feature; it's not currently doable by this plugin or via CSS, and would be very hard for any plugin to do in a way that didn't break other things.  (In fact, implementing support for it in Obsidian core would probably still break a lot of themes and plugins.)

In any case, it's not implementable at all by this plugin.
