### ISSUE TITLE
Expand / Collapse at this level - Not Working

### ISSUE THREAD

**Issue by Irshaadv** [pjeby/tag-wrangler#77]
Hi there, 

Thanks very much for a great plugin!

I seem to have a bug (or I'm doing something really dumb). "Expand / Collapse tags at this level" does nothing. Any ideas?

Thanks again!
Irshaad

**Comment by pjeby** [comment]
Hm.  Looks like something changed in Obsidian 1.x that affects that.  I've added a fix to 0.5.7, so an update should get you sorted.

**Comment by Irshaadv** [comment]
Awesome, works!

Thanks so much :)
