### ISSUE TITLE
Resize required for android 

### ISSUE THREAD

**Issue by Awsalfered** [pjeby/tag-wrangler#79]
Hi, I'm using tag wrangler in android 12 on poco m3.
Renaming tag window requires auto resizing feature. 
Screenshot uploaded. 
Thanks 

![Screenshot_2023-04-14-07-21-53-434_md.obsidian.jpg](https://user-images.githubusercontent.com/50650614/231937278-ebb6c94c-ed76-464a-9ab6-a05fac514a92.jpg)

**Comment by pjeby** [comment]
I don't use Obsidian mobile and don't know what you mean by "auto resizing feature" in this context.  Does it not work in landscape mode?

**Comment by pjeby** [comment]
Closing due to six months with no response.
