### ISSUE TITLE
FR: allow the user to drag a tag in the tag pane to another to make the first one become a subtag of the second

### ISSUE THREAD

**Issue by ghweili** [pjeby/tag-wrangler#80]
This would make it make easier to reorganize the tags, especially when the user has a large nested tag system.

**Comment by pjeby** [comment]
This is now supported in 0.6.0 - if you drag a tag and drop it on a tag in the tag pane, you'll be prompted to rename the dragged tag, with the default filled in to make it a child of the tag you dropped it on.
