### ISSUE TITLE
Open Tag Page doesn't find pages with additional Aliases.

### ISSUE THREAD

**Issue by jacksodj** [pjeby/tag-wrangler#82]
If I create a tag page, and add any additional aliases the "Open tag page" changes to "Create Tag page". 
If I delete the second alias, the context menu flips back to "Open tag page".

scenario where this is useful. I have a topic page with a decently long name, and everyone refers to it with an Acronym.
The tag is an acronym.

Friends based example.
so I would like:

```
Title: Weekly Estimated Net Usage Statistics
---
Aliases: WENUS, [ "#Reports/WENUS"]
---
## Description
## Purpose

```

I have tried it with CRLF formatted Alias syntax in front matter as well.

**Comment by pjeby** [comment]
What you've posted above is invalid YAML, and invalid front matter.  The correct formatting would be:

```
---
Title: Weekly Estimated Net Usage Statistics
Aliases: [ WENUS, "#Reports/WENUS" ]
---
## Description
## Purpose
```

Or:

```
---
Title: Weekly Estimated Net Usage Statistics
Aliases:
  - WENUS
  - '#Reports/WENUS'
---
## Description
## Purpose
```

Notice that:

- All the metadata must be contained between two `---` lines, without anything above the first one
- The *entire* list of aliases must be a valid YAML list, either in flow format (`[ item, item, ...]`) or indented list format
- Aliases containing `#`, commas, and certain other punctuation must be enclosed in straight single or straight double quotes

These are rules of the YAML format and of Obsidian metadata; they're not specific to Tag Wrangler.

**Comment by jacksodj** [comment]
ok, so the square brakcets in the autoget tag page are JSON format in the front matter. 
Gotcha. 
took that out and works like a champ. Cheers.
