### ISSUE TITLE
Exclude a folder 

### ISSUE THREAD

**Issue by GitHubFriendlyUser** [pjeby/tag-wrangler#84]
Hello, 

I have a template folder with tags. I already excluded the folder, so I don't have the tags with dataview. But I have them with Tag Wrangler, and it's pretty annoying. 

How can I do to exclude them ? 

Thank you in advance for your help !

**Comment by guidovicino** [comment]
Hello,

first things first: thank you for yours plugin to every contributors. If you use Templater (or also Template) plugins to personalize plugins, i.e.:

---
tags: [article, when/<% tp.file.last_modified_date("YYYY") %>, when/<% tp.file.last_modified_date("MM") %>, when/<% tp.file.last_modified_date("YYYY") %>/<% tp.file.last_modified_date("MM") %>, when/<% tp.file.last_modified_date("dddd") %>]
date: <% tp.file.last_modified_date("YYYY-MM-DDTHH:mm:ss U (UTC +01:00)") %>
---

The Templater escape characters like "<$" will be seen by tag wrangler as tags:

https://ibb.co/TY0LQ7P

These tags can be excluded from the Searches but you will see in the tag wrangler list. 

This behaviour can happens also if you have some code snippets in your notes.

It will be nice have the possibility in the plugins settings excluding some dirs (like templates) from tag wrangler scope.

**Comment by pjeby** [comment]
The behavior you're describing has nothing to do with Tag Wrangler, it's just how Obsidian handles tags.  Even if you disable or uninstall Tag Wrangler, you would see the exact same thing happening in the tag pane.

If you want this to change, you need to report this as an issue (or feature request) on the Obsidian forums to request that Obsidian not include tags from search-excluded folders.

**Comment by guidovicino** [comment]
> The behavior you're describing has nothing to do with Tag Wrangler, it's just how Obsidian handles tags. Even if you disable or uninstall Tag Wrangler, you would see the exact same thing happening in the tag pane.
> 
> If you want this to change, you need to report this as an issue (or feature request) on the Obsidian forums to request that Obsidian not include tags from search-excluded folders.

Ok! Thank you for your clarification and thank you again for your plugin and your effort!

**Comment by pjeby** [comment]
In the meantime, you may want to try a workaround like this:

```yaml
---
'tags<% "" %>': [article, when/<% tp.file.last_modified_date("YYYY") %>, when/<% tp.file.last_modified_date("MM") %>, when/<% tp.file.last_modified_date("YYYY") %>/<% tp.file.last_modified_date("MM") %>, when/<% tp.file.last_modified_date("dddd") %>]
date: <% tp.file.last_modified_date("YYYY-MM-DDTHH:mm:ss U (UTC +01:00)") %>
---
```

I don't know if that will work correctly in Templater, as I'm making the assumption that `<% "" %>` will output nothing in the resulting file.

Anyway, the trick here is that when Obsidian reads the file, it sees a field called `tags<% "" %>` and ignores it because it's not just "tags".  But when used as a template, the resulting file will have a field called  `'tags'`, and Obsidian will read it.

Again, not sure if that will actually work as I'm making an assumption about Templater that may not be accurate.  But some form of this idea should be doable, you just need to enclose the field name (tags) in single quotes, and get Templater to output an empty string somewhere in that name (so that Obsidian sees templater code in the name and ignores the field, but when the template is executed, there's nothing there and Obsidian sees a tags field).

**Comment by guidovicino** [comment]
> In the meantime, you may want to try a workaround like this:
> 
> ```yaml
> ---
> 'tags<% "" %>': [article, when/<% tp.file.last_modified_date("YYYY") %>, when/<% tp.file.last_modified_date("MM") %>, when/<% tp.file.last_modified_date("YYYY") %>/<% tp.file.last_modified_date("MM") %>, when/<% tp.file.last_modified_date("dddd") %>]
> date: <% tp.file.last_modified_date("YYYY-MM-DDTHH:mm:ss U (UTC +01:00)") %>
> ---
> ```
> 
> I don't know if that will work correctly in Templater, as I'm making the assumption that `<% "" %>` will output nothing in the resulting file.
> 
> Anyway, the trick here is that when Obsidian reads the file, it sees a field called `tags<% "" %>` and ignores it because it's not just "tags". But when used as a template, the resulting file will have a field called `'tags'`, and Obsidian will read it.
> 
> Again, not sure if that will actually work as I'm making an assumption about Templater that may not be accurate. But some form of this idea should be doable, you just need to enclose the field name (tags) in single quotes, and get Templater to output an empty string somewhere in that name (so that Obsidian sees templater code in the name and ignores the field, but when the template is executed, there's nothing there and Obsidian sees a tags field).

Worked like a charm! Thank you very much and have a nice weekend!

**Comment by pjeby** [comment]
@GitHubFriendlyUser does this address your problem as well?

**Comment by pjeby** [comment]
An improved workaround, courtesy of Luke on Discord:

```yaml
<% "---" %>
tags: [article, when/<% tp.file.last_modified_date("YYYY") %>, when/<% tp.file.last_modified_date("MM") %>, when/<% tp.file.last_modified_date("YYYY") %>/<% tp.file.last_modified_date("MM") %>, when/<% tp.file.last_modified_date("dddd") %>]
date: <% tp.file.last_modified_date("YYYY-MM-DDTHH:mm:ss U (UTC +01:00)") %>
<% "---" %>
```

This version is cleaner to read and tricks Obsidian into ignoring *all* the metadata fields, but when the template is expanded it'll be considered metadata.
