### ISSUE TITLE
[Feature] Delete tag

### ISSUE THREAD

**Issue by alxgoldstn** [pjeby/tag-wrangler#86]
I would love to see an option that allows for right-click --> "Remove tag" --> **Goes through the vault and changes all instances of `#tag` to `tag`**

Should probably pop up a warning first: "This is destructive and will rewrite all instances of `#tag` with `tag`. Are you sure?"

**Comment by pjeby** [comment]
That method of deletion wouldn't work for metadata tags - they'd still be tags from Obsidian's point of view if you did that.

**Comment by alxgoldstn** [comment]
Hm, can you clarify? I'm not sure what you mean. 

If I create a `#tag` in Obsidian, it shows up in my tag pane. If I then remove the `#` prefix, the tag disappears from the tag pane. The tag is removed once all `#tags` are removed, no?

**Comment by pjeby** [comment]
Metadata tags are specified in a note's metadata, like so:

```yaml
---
Tags: xyz abc def
---
Note text goes here
```

If you paste that into a note you'll see tags #xyz, #abc, and #def appear in the tag pane.  They don't have `#` in front of them in the note, so removing the `#` will not "delete" the tag.

The reason I haven't implemented any sort of delete feature is that it's basically impossible to do it in a way that everyone who wants a delete feature would approve of.  (See previous discussion in #4, for example.)  Everyone has a proposal for something that could work for *their* notes and tags, but not for other people who want it to work a different way.

**Comment by utpalsavliya** [comment]
We can implement some checkboxes in the confirmation dialogue so that the person can select the behavior according to their needs. Everyone will approve it that way! 😉
