### ISSUE TITLE
Problem building dev.

### ISSUE THREAD

**Issue by mariomui** [pjeby/tag-wrangler#93]
<img width="740" alt="Screen Shot 2023-06-03 at 2 47 33 AM" src="https://github.com/pjeby/tag-wrangler/assets/29618692/12fff0da-72fe-4b3f-9d08-1e0a85c5b89e">

when i run pnpm dev , this is my result.

**Comment by pjeby** [comment]
Try using node 16 or earlier; ophidian/build doesn't support node 18 yet.

**Comment by mariomui** [comment]
"ophidian": "github:pjeby/ophidian",
+ ophidian <- @ophidian/core 0.0.12

i think ophidian links to core which doesn't have a build folder.

I just ran it on 18 16 and 14 fine when using @obsidian/build
core doesnt have an exported .build folder. So no subpath.
In summary, ophidian doesn't link to @ophidian, it links to @ophidian/core

**Comment by pjeby** [comment]
I've pushed an updated version that fixes that, and also added the missing exports that node 18+ complains about.
